### ISSUE TITLE
Add Continuous Deployment to this repo

### ISSUE THREAD

**Issue by Zeitsperre** [roocs/roocs-utils#117]
* roocs-utils version: Current
* Python version: Any
* Operating System: N/A

### Description

Currently, the deployment method for adding new versions to PyPI is entirely manual. We should leverage GitHub Workflows to make this easier.

For an example, see: 
* https://github.com/roocs/clisops/blob/master/.github/workflows/publish-pypi-production.yml and
* https://github.com/roocs/clisops/blob/master/.github/workflows/prepare-release.yml

**Comment by cehbrecht** [comment]
@Zeitsperre we like to move roocs-utils into clisops: #107

**Comment by Zeitsperre** [comment]
This is obsolete. Closing.
