### ISSUE TITLE
Import of `clisops.CONFIG` does not load clisops-specific `roocs.ini` - unless we make it always load the configs

### ISSUE THREAD

**Issue by agstephens** [roocs/roocs-utils#16]
We should add this test:

```
from clisops import  CONFIG

def test_local_config_loads():
    assert 'clisops:read' in CONFIG
    assert 'file_size_limit' in CONFIG['clisops:read']
```

It currently fails, because:

- inside `clisops/__init__.py` we load `roocs_utils` which activates `roocs_utils/__init__.py` - which loads the CONFIG from the perspective of `roocs-utils` first. 
- then, `clisops/__init__.py` tries to load the CONFIG with the arg `(clisops)` - but it has already been loaded.

We need a slightly different solution.

**Comment by agstephens** [comment]
FIX FOR NOW: just modify the loader so that it always loads all config files.

Come back and fix this later.

**Comment by agstephens** [comment]
Currently the `clisops/__init__.py` does:

```
import clisops
CONFIG = get_config(clisops)
```

Maybe it should be replaced with:

```
CONFIG = get_config(os.path.dirname(__file__))
```

Then `get_config` will then say:
```
_CONFIGS_READ = []

def get_config(dr):
      if dr not in _CONFIGS_READ:
           load_config(dr)
```

**Comment by Zeitsperre** [comment]
I think this may have been fixed in this pull request: https://github.com/roocs/clisops/pull/216
