### ISSUE TITLE
is_level identifies text coordinates as level

### ISSUE THREAD

**Issue by ellesmith88** [roocs/roocs-utils#43]
* roocs-utils version: 0.1.5
* Python version:
* Operating System:

@agstephens @cehbrecht 
### Description

I came across a dataset where `get_coord_type`  in `roocs_utils.xarray_utils.xarray_utils` identifies a text coordinate as `level` due to `is_level`. 

An example is the `sector` coordinate in the dataset `CMIP6.ScenarioMIP.IPSL.IPSL-CM6A-LR.ssp245.r1i1p1f1.Lmon.landCoverFrac.gr.v20190119`

```
<xarray.DataArray 'sector' (type: 15)>
dask.array<open_dataset-00cd8727d8f646c1f67efe51ce21e735sector, shape=(15,), dtype=|S255, chunksize=(15,), chunktype=numpy.ndarray>
Coordinates:
    sector   (type) |S255 dask.array<chunksize=(15,), meta=np.ndarray>
Dimensions without coordinates: type
Attributes:
    name:           sector
    standard_name:  model_level_number
    long_name:      Vegetation or Land Cover Type
    units:          1
```

It has values:
```
ds.sector.values
array([b'bare_ground', b'tropical_broad_leaved_evergreen',
       b'tropical_broad_leaved_raingreen',
       b'temperate_needleleaf_evergreen',
       b'temperate_broad_leaved_evergreen',
       b'temperate_broad_leaved_summergreen',
       b'boreal_needleleaf_evergreen', b'boreal_broad_leaved_summergreen',
       b'boreal_needleleaf_summergreen', b'temperate_C3_grass',
       b'C4_grass', b'C3_agriculture', b'C4_agriculture',
       b'tropical_C3_grass', b'boreal_C3_grass'], dtype='|S255')
```

With older versions of `roocs_utils` it isn't identified as `level` so this has come about from using `cf-xarray` in `is_level`:
```
def is_level(coord):
    """
    Determines if a coordinate is level.

    :param coord: coordinate of xarray dataset e.g. coord = ds.coords[coord_id]
    :return: (bool) True if the coordinate is level.
    """
    if "vertical" in coord.cf and coord.cf["vertical"].name == coord.name:
        return True

    if hasattr(coord, "positive"):
        if coord.attrs.get("positive", None) == "up" or "down":
            return True

    if hasattr(coord, "axis"):
        if coord.attrs.get("axis", None) == "Z":
            return True

    return False
```

In `subset_level` in `clisops` this isn't identified as level because we use `get_coord_by_type(da, "level", ignore_aux_coords=True)` so as an auxiliary coordinate it is ignored and `Exception: subset_level requires input data that has a recognisable "level" coordinate.` is raised.

How should we handle this? Do we want it to be identified as level or not?

**Comment by agstephens** [comment]
Tagging @Zeitsperre @huard - you might have thoughts on this issue.

**Comment by huard** [comment]
Hi @agstephens 
This should not be a level. I don't see how cf-array identifies it as a vertical level though. I'm missing something.

**Comment by agstephens** [comment]
@ellesmith88: please have a look into the cf-xarray code to see where it is making this decision. Might be worth forking it and writing a test - just in case you need to submit a pull request. Thanks

**Comment by sol1105** [comment]
I don't know if this is of interest regarding this issue, but there are also axes like "spectband" or "scatratio" where it might be relevant whether they are identified as levels or not. A full list of the axes for CMIP6 can be found here (of which maybe the ones who are not a vertical axis, are of interest): http://clipc-services.ceda.ac.uk/dreq/index/grids.html
