### ISSUE TITLE
Demonstrate intake format for inventory 

### ISSUE THREAD

**Issue by ellesmith88** [roocs/roocs-utils#70]
### Description

Create a notebook demonstrating how to use the intake catalog in place of the inventory.

**Comment by ellesmith88** [comment]
@cehbrecht  I've created an example catalog, using 500 datasets that can be used to demonstrate how to use it.

[catalog.zip](https://github.com/roocs/roocs-utils/files/6419650/catalog.zip)

**Comment by cehbrecht** [comment]
I have added a demo notebook to show the dataset aggregation with intake/pandas:
https://nbviewer.jupyter.org/github/roocs/rooki/blob/master/notebooks/demo/demo-intake-ecmwf.ipynb

**Comment by cehbrecht** [comment]
@ellesmith88 there is format issue with `c3s.yml` catalog. The `cache` is expecting a `list`. See here:

https://github.com/cp4cds/c3s_34g_manifests/blob/0619087a1a5c464ba8c7d1ac994d244e1951f2d2/intake/catalogs/c3s.yaml#L5-L7

**Comment by cehbrecht** [comment]
@ellesmith88 @agstephens Could we add the demo catalog to our manifest repo?
https://github.com/cp4cds/c3s_34g_manifests

We could load it then directly from `intake`.

**Comment by ellesmith88** [comment]
@cehbrecht I have updated the catalogue now see https://github.com/roocs/roocs-utils/pull/72. 

Shall I add the demo catalogue here https://github.com/cp4cds/c3s_34g_manifests/tree/master/intake under a demos folder?

**Comment by cehbrecht** [comment]
> Shall I add the demo catalogue here https://github.com/cp4cds/c3s_34g_manifests/tree/master/intake under a demos folder?

sounds good 👍

**Comment by ellesmith88** [comment]
@cehbrecht added: https://github.com/cp4cds/c3s_34g_manifests/tree/master/intake/demos
