### ISSUE TITLE
pip install failing because of psycopg2

### ISSUE THREAD

**Issue by ellesmith88** [roocs/roocs-utils#74]
I just released `roocs-utils` after merging the catalog maker changes branch. Now when I try to pip install I get an error and have to run `brew install postgresql` to be able to install `psycopg2` , even though `psycopg2` seems to pip install fine for the tests without any extras..

Is this a problem for you @agstephens @cehbrecht ?

If so should I remove the `abcunit-backend` dependency and put in the readme/ installation that it needs to be installed for the catalogue maker?

**Comment by agstephens** [comment]
@ellesmith88 Yes, that is a good solution. You can put a check in the relevant catalogue maker code that does a `try/except` at the top to see if it can import `pscyopg2` - if it fails it can raise an Exception. Then you can just document the dependency and remove it from the main `requirements.txt`.

**Comment by ellesmith88** [comment]
Thanks @agstephens :)

**Comment by ellesmith88** [comment]
Updated to v0.4.2
